### ISSUE TITLE
Funções Banco

### ISSUE THREAD

**Issue by JefersonBLuz** [JefersonBLuz/Projeto_TCC#9]
# Criar funções para banco de dados.

## Usuário padrão:

* Criar/Atualizar/Visualizar Família
* Criar/Atualizar/Visualizar Motorista
* Criar/Atualizar/Visualizar Veículo 

## Usuário View

* Visualizar Família
* Visualizar Motorista
* Visualizar Veículo 

## Usuário ADM

... Usuário Padrão
* Criar/Atualizar/Visualizar Usuário

**Acrescentar no banco de dados de usuário**

#1 Acrescentar Usuário Ativo (Boolean)

## Usuário Master

... Usuário ADM + Drop

**Comment by Davidovtch** [comment]
O ativo seria para verificar se ele ainda trabalha no projeto,decidindo se ele pode ou não logar correto?

**Comment by JefersonBLuz** [comment]
Isso. 

> O ativo seria para verificar se ele ainda trabalha no projeto,decidindo se ele pode ou não logar correto?

**Comment by JefersonBLuz** [comment]
Funções cosntruidas
